// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import {NextIntlClientProvider} from "next-intl";
import {getLocale, getMessages} from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cartridge site 2.0 test",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  let messages: Record<string, unknown>;
  try {
    messages = await getMessages();
  } catch {
    // Fallback als het messages-bestand ontbreekt
    messages = (await import("@/messages/nl.json")).default as Record<string, unknown>;
  }

  return (
    <html lang={locale} suppressHydrationWarning>
    
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className=" text-black p-4 flex items-center justify-center">
              <Link href="/"><Image src="next.svg" alt="Logo" width={64} height={64}/></Link> 
              <nav className="ml-8">
                  <ul className="flex space-x-6">
                      <li>
                          <Link href="/" className="hover:text-gray-600">Home</Link>
                      </li>
                      <li>
                          <Link href="/products" className="hover:text-gray-600">Products</Link>
                      </li>
                      <li>
                          <Link href="/cart" className="hover:text-gray-600">Cart</Link>
                      </li>
                      <li>
                          <Link href="/contact" className="hover:text-gray-600">Contact</Link>
                      </li>
                  </ul>
              </nav>
             
          </header>
        <NextIntlClientProvider messages={messages} locale={locale} key={locale}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}